# Generated by Django 4.2.11 on 2024-04-03 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ai_Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('shumnail', models.ImageField(upload_to='aimodules/thumnails')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.ai_node')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
