# Generated by Django 4.2.11 on 2024-04-05 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimodules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ai_module',
            name='start_node',
        ),
    ]
