# Generated by Django 4.2.11 on 2024-04-05 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aimodules', '0002_remove_ai_module_start_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ai_module',
            name='shumnail',
        ),
    ]
