# Generated by Django 4.2.11 on 2024-04-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodules', '0003_remove_ai_module_shumnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_module',
            name='shumnail',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
